name: frontend-build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: echo "Installing dependencies using yarn"
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - run: echo "Creating production optimised build"
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - run: echo "Running Test Cases."
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - run: echo "Reporting code coverage to CodeCov."
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml
          flags: uitests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - run: echo "Generating frontend docs."
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: generate-docs